#! /usr/bin/python
import chatterfox, sys

if len(sys.argv) == 2:
  chatterfox.client_handler(sys.argv[1])

elif len(sys.argv) == 1:
  chatterfox.client_handler()

else:
  print >>sys.stderr, 'Example usage: chatter [ <host> ]'
  sys.exit(2)
